name: saleor_app_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  animated_snack_bar: ^0.3.0
  another_xlider: ^1.1.2
  auto_animated: ^3.1.0
  auto_size_text: ^3.0.0
  awesome_snackbar_content: ^0.1.0
  badges: ^3.0.2
  beamer: ^1.5.3
  blur: ^3.1.0
  cached_network_image: ^3.2.3
  card_loading: ^0.3.0
  cloud_firestore: ^4.3.1
  collection: ^1.17.0
  cross_file: ^0.3.3+4
  cupertino_icons: ^1.0.2
  custom_radio_grouped_button: ^2.1.2+2
  dartz: ^0.10.1
  drop_down_list: ^0.0.4
  dropdown_button2: ^1.9.2
  dropdown_search: ^5.0.5
  easy_autocomplete: ^1.6.0
  easy_rich_text: ^1.1.0
  email_validator: ^2.1.17
  equatable: ^2.0.5
  extended_phone_number_input: ^1.0.2
  file_picker: ^5.2.5
  file_selector: ^0.9.2+3
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_database: ^10.0.11
  firebase_phone_auth_handler: ^1.0.8
  firebase_storage: ^11.0.10
  firebase_messaging: ^14.2.6
  firebase_analytics: ^10.1.5
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_chips_input: ^2.0.0
  flutter_image_slideshow: ^0.1.4
  flutter_launcher_icons: ^0.11.0
  flutter_login: ^4.1.1
  flutter_multi_formatter: ^2.2.1
  flutter_onboarding_slider: ^1.0.8
  flutter_pw_validator: ^1.5.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.6.0
  flutter_secure_storage: ^7.0.1
  flutter_typeahead: ^4.3.3
  permission_handler: ^10.2.0
  flutter_verification_code: ^1.1.6
  flutter_wall_layout: ^2.1.1
  footer: ^0.0.4
  form_builder_extra_fields: 8.3.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  functional_enum: ^1.1.5
  geocoding: ^2.0.5
  get_it: ^7.2.0
  getworld: ^1.1.0
  google_maps: ^6.2.0
  google_maps_flutter: ^2.2.3
  google_maps_flutter_web: ^0.4.0+5
  graphql_flutter: ^5.1.0
  http: ^0.13.5
  image_watermark: ^0.0.5
  image_zoom_on_move: ^1.0.0
  injectable: ^2.1.0
  input_quantity: ^1.1.4
  internet_connection_checker_plus: ^1.0.1
  intl_phone_field: ^3.1.0
  ionicons: ^0.2.1
  loading_overlay: ^0.3.0
  location: ^4.4.0
  lottie: ^2.1.0
  material_dialogs: ^1.1.4
  motion_toast: ^2.6.4
  open_street_map_search_and_pick: ^0.0.15
  paginated_search_bar: ^1.1.2
  pinch_zoom: ^1.0.0
  quantity_input: ^1.0.2
  restart_app: ^1.1.2
  rive: ^0.10.1
  rounded_loading_button: ^2.1.0
  scroll_snap_list: ^0.9.1
  search_choices: ^2.2.1
  select_dialog: ^2.0.0
  stamp_image: ^0.0.2
  shared_preferences: ^2.0.18
  timelines: ^0.1.0
  url_launcher: ^6.1.7
  url_strategy: ^0.2.0
  uuid: ^3.0.7
  web_socket_channel: 2.2.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.3
  mockito: ^5.3.2
  change_app_package_name: ^1.1.0

flutter_icons:
  android: "launcher_icon"
  background_color: "#ffffff"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 19 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lottie/
    - assets/image/
    - assets/fonts/

  fonts:
    - family: Hacen
      fonts:
        - asset: assets/fonts/hacen_Normal.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf

    - family: Behdad
      fonts:
        - asset: assets/fonts/Behdad-Regular.ttf

    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazirmatn-Thin.ttf
          weight: 100
        - asset: assets/fonts/Vazirmatn-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Vazirmatn-Light.ttf
          weight: 300
        - asset: assets/fonts/Vazirmatn-Regular.ttf
          weight: 400
        - asset: assets/fonts/Vazirmatn-Medium.ttf
          weight: 500
        - asset: assets/fonts/Vazirmatn-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Vazirmatn-Bold.ttf
          weight: 700
        - asset: assets/fonts/Vazirmatn-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Vazirmatn-Black.ttf
          weight: 900
